### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by brennovich** [brennovich/feuerundflamme.xyz#3]
- [x] TODO: Add the about page text

**Comment by rbxwall** [comment]
**ABOUT**

**Bündnis Feuerundflamme**
Das Bündnis Feuer&Flamme engagiert sich am Dragonerareal mit Workshops rund um den offenen Keramiktreff, Back- und Räucherhappenings am Backhauswagen und Einladungen zum gemeinsamen Kochen und Essen mit der Zusammküche.
Das Kochen und viele verwandte Tätigkeiten finden hauptsächlich im Privaten oder Verbogenen statt. Das partizipative Kochen möchte dazu beitragen, ein neues Verständnis der häuslichen Tätigkeit als wertvolle, produktive Einheit zu begreifen, die sozial engagierter ist und den Kontext stärker miteinbezieht als die gängige Idee des Haushalts als private Konsumeinheit.
Seit einem Jahrzehnt befeuern aktive Bürger*innen-Initiativen die öffentliche Diskussion über die Zukunft des Rathausblocks und haben daraus inzwischen ein Modellprojekt der Stadtentwicklung gemacht. Das Bündnis Feuer&Flamme feuert weiter.

**Backhauswagen**
Der Backhauswagen ist eine kostenlose, zugängliche, mobile, versorgende und fürsorgende Infrastruktur für ein Areal in Transformation: ein Brotbackofen, Gärkammer und Räucherofen im Auto-Anhänger-Format. Zur Zeit steht der Backhauswagen auf der Brache vor der Plangarage auf dem Dragonerareal (Garagen hinter der LPG-Tankstelle an der Obentrautstraße) und engagiert sich im Bündis Feuer&Flamme. 

**KeramikTreff**
Der KeramikTreff im Rathausblock ist ein informeller, niedrigschwelliger Ort des Austauschs, der Nachbarschaft und des gemeinsamen künstlerischen Tätigseins. Er ist ein demokratischer Aktions- und Partizipations-Treffpunkt, ein Labor für und aus der Nachbarschaft. Das Angebot des KeramikTreffs ergänzt seit Sommer 2020 das kooperative, gemeinwohlorientierte Planungsverfahren zum Modellprojekt Rathausblock mit künstlerisch
geprägten Momenten der Begegnung und des Austauschs.

**Zusammenküche**
Die ZusammenKüche ist ein Ort und eine Praxis, die die Bedürfnisse der jetzigen und künftigen Mieter*innen und Nachbarn*innen erforscht und sie dazu ermutigt, Essen als ästhetisches Mittel der Kommunikation und des Austauschs zu betrachten.
Durch die ZusammenKüche werden neue Szenarien für Lebensmittel erfunden und ihre Möglichkeiten an der Schnittstelle von Alltag und Kunst neu überdacht. 
In den Workshops, Menüs und kulinarischen Installationen erforschen die Mitmachenden den sozialen Kontext der Gerichte, während die sie ganz konkrete sinnliche und soziale Räume schaffen.

**feuerexperimente4u**
Eine Veranstaltungsreihe des Bündnis Feuer&Flamme für ein Areal in Transformation. 
Laufzeit: Juni – Oktober 2022. Gefördert von DRAUSSENSTADT.

**Comment by rbxwall** [comment]
<img width="1217" alt="Bildschirmfoto 2022-10-14 um 19 34 12" src="https://user-images.githubusercontent.com/115560099/195907221-ef0ada7c-eee7-426a-9563-17880b869511.png">

**Comment by brennovich** [comment]
Starting with the styling ;)

![Image](https://user-images.githubusercontent.com/379894/201475427-adf44e6e-11a9-4534-9a94-176bfa80b89f.png)

**Comment by rbxwall** [comment]
Juhuuu :) <3
